project:
  type: website

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
    - "files/**"
    - "etc/**"

    # Things that need to be at the site root
    - ".htaccess"
    - "LiveSearchSiteAuth.xml"
    - "keybase.txt"
    - "y_key_31e0c4105fc75710.html"
    - "pgp_ath.asc.txt"

freeze: true

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

# Metadata stuff
pagetitle: "{{< meta title >}} | Elías Aburto"
author-meta: "Elías Aburto"

website:
  title: "Elías Aburto"
  description: "Elías Aburto is an research assistant  at Pacific's University."
  favicon: "/files/favicon-512.png"
  site-url: "https://www.andrewheiss.com"
  repo-url: "https://github.com/andrewheiss/ath-quarto"

  google-analytics: "UA-527449-5"

  twitter-card: 
    image: "/files/profiles/twitter-card-large.png"
    card-style: summary_large_image
    creator: "@andrewheiss"
    site: "@andrewheiss"

  open-graph: 
    image: "/files/profiles/twitter-card-large.png"
    locale: en_US
  
  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Blog"
        file: blog/index.qmd
      - text: "Research"
        file: research/index.qmd

    
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:elias.abucamac@gmail.com"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/EliasAburtoC
        rel: me
      - text: "{{< iconify bi youtube size=1.1em title='YouTube' >}}"
        href: https://www.youtube.com/@eliasaburto2018
        rel: me
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/elías-aburto-camacllanqui
        rel: me
  
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Elías Aburto</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
      <span class="faux-block">{{< fa key >}} [PGP public key]({{< var pgp.key >}}) &emsp; {{< fa fingerprint >}} Fingerprint:</strong><br><span class="fingerprint">{{< var pgp.fingerprint >}}</span></span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme: 
      - html/ath.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
