{
  "hash": "6a4335b739ec795bd70061505c569ffd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Consumer behavior: Determinants of COVID-19 vaccination intention using Planned Behavior Theory\"\ndate: 2023-08-15\ndescription: \"I make a secondary analysis using multiple regression analysis. I used the data from Drążkowski & Trepanowski (2022) which was published in a open source repository.\"\nimage: \"img/covid.jpg\"\ncategories:\n  - covid-19\n  - multiple regression analysis\n  - Planned Behavior theory\n  - r\n\n---\n\n\n# Introduction\n\n<!-- Adjust size using width and height attributes -->\n<img src=\"img/covid.jpg\" alt=\"COVID-19 vaccination\" width=\"350\" height=\"500\" style=\"float:right; margin: 0 0 10px 10px;\">\n\n**Problem of research:** What are the determinants of COVID-19 vaccination intention?\n\n**Objective:**\nTo identify the determinants of COVID-19 vaccination through an application of the Theory of Planned Behavior.\n\n**Hypothesis:**\n\n- H1: Control beliefs have a direct impact on COVID-19 vaccination intention.\n\n- H2: Utility beliefs have a direct impact on COVID-19 vaccination intention.\n\n- H3: Social norm beliefs have a direct impact on COVID-19 vaccination intention.\n\n\n\n\n\n# Methodology\n\n**Sample:** 551 Polish participants.\n\n\n**Study Design:** The original research used a structural equation modeling (Drążkowski & Trepanowski, 2022)  but, in this case, I'm using a multiple linear regression to explain the necessary proccess that a research must have with this design. Therefore, I'm doing a secondary analysis.\n\n\n# Multiple Regression Analysis: Step by step\n\nSteps to prove the hypothesis\n\nA. Model Evaluation\n\n1. Regression coeficients and r-square\n2. Interpretation\n\nB. Regression Model Assumtions\n\n1. Lineality between IVs and Dv\n2. Independence of observations: The observation from our model are independent.\n3. Homoscedasticity: The errors from our model have equal variance.\n4. Normality of Errors: The errors from our model are normally distributed.\n\nC. Additional information\n\n1. Multicollinality: evaluate if the IVs are redundant.\n2. Diagnostics: to assess the overall goodness-of-fit.\n\n\n## A. Model Evaluation\n\n### A1. Regression coeficients and r-square\n\n\nInstall packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"ggplot2\")\n#install.packages(\"dplyr\")\n#install.packages(\"broom\")\n#install.packages(\"ggpubr\")\n#install.packages(\"tidyverse\")\n```\n:::\n\n\nload the packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"foreign\")\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(broom)\nlibrary(ggpubr)\nlibrary(tidyverse)\nlibrary(readr)\nlibrary(car)\n```\n:::\n\n\n\nLoad the database\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMydata <- read.spss(\"data/COVID_data.sav\",to.data.frame=T,use.value.labels=FALSE)\n\nView(Mydata)\n\nsummary(Mydata$SE_Total)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   3.00   12.00   15.00   15.42   18.00   21.00 \n```\n\n\n:::\n:::\n\n\nPerform the linear regression analysis\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nIntention_lm <- lm(IN_Total ~ SN_Total + BC_Total + AT_Total, data = Mydata)\nsummary(Intention_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IN_Total ~ SN_Total + BC_Total + AT_Total, data = Mydata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.4622  -1.2412   0.1199   1.3464  11.0907 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -1.71571    0.36855  -4.655 4.07e-06 ***\nSN_Total     0.36218    0.03976   9.109  < 2e-16 ***\nBC_Total     0.29052    0.03483   8.341 6.00e-16 ***\nAT_Total     0.45369    0.03504  12.946  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.457 on 547 degrees of freedom\nMultiple R-squared:  0.7865,\tAdjusted R-squared:  0.7853 \nF-statistic: 671.5 on 3 and 547 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n### A2. Interpretation of Bs ajusted\n\nAbout Subjective Norms,\n\nPrediction: For each point obtained in the scale of subjective norms, the intenton to COVID-19 vaccination intention will increase 0.36 points. \n\nExplanation: Subjective norms had a direct and positive effect  on COVID-19 vaccination intention it was statistically significant.\n\nAbout Behavioral Control,\n\nPrediction: For each point obtained in the scale of Behavioral Control, the intenton to COVID-19 vaccination intention will increase 0.29 points. \n\nExplanation: Behavioral Control had a direct and positive effect on COVID-19 vaccination intention and it was statistically significant.\n\n\nAbout Attitude Toward Covid-19 vaccination,\n\nPrediction: For each point obtained in the scale of Attitude Toward Covid-19 vaccination, the intenton to COVID-19 vaccination intention will increase 0.45 points. \n\nExplanation: Attitude Toward Covid-19 vaccination had a direct and positive effect on COVID-19 vaccination intention  and it was statistical significance.\n\n\nThe model with these three determinants explain 78% of variance of COVID-19 vaccination intention.\n\n\n## B. Regression Model Assumtions\n\n### B1. Lineality between IVs and Dv\n\nThe relationship between IVs and DV must be lineal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(IN_Total ~ SN_Total, data = Mydata)\nabline(lm(IN_Total ~ SN_Total, data = Mydata), col = \"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\nIt's observed that there is a linear relationship between Subjective Norms and COVID-19 Vaccination Intention\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(IN_Total ~ BC_Total, data = Mydata)\nabline(lm(IN_Total ~ BC_Total, data = Mydata), col = \"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\nIt's observed that there is a linear relationship between Behavioral Control and COVID-19 Vaccination Intention\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(IN_Total ~ AT_Total, data = Mydata)\nabline(lm(IN_Total ~ AT_Total, data = Mydata), col = \"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\nIt's observed that there is a linear relationship between Attitude toward Covid-19 vaccination and COVID-19 Vaccination Intention\n\n\n\n### B2. Independence of observations \n\nThe covariances of errors must be cero.\n\nThe observation from our model are independent. This was fulfilled when each observation was made by one participant.\n\nEvaluation:\n\nUse the Durbin-Watson Test. This is useful to test autocorrelation of residuals that must be cero.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car) # In this package is Durbin-Watson Test\n\ndurbinWatsonTest(Intention_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1      -0.1210717      2.241997       0\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n:::\n\n\nH0: There is not correlation among the residuals.\nH1: The residuals are autocorrelated.\n\n\nIf the p-value is less than 0.05, you would reject the null hypothesis and conclude that there is evidence of autocorrelation in the residuals.\n\nIf the p-value is greater than 0.05, you would fail to reject the null hypothesis, suggesting that there is insufficient evidence to conclude that there is autocorrelation in the residuals.\n\n\nIn this result, since the p-value (0.002) is less than 0.05, we would conclude that there is evidence of autocorrelation in the residuals.\n\n\nAlthough, It was mention that D-W statistic is between 0 to 4. Values between 1.5 and 2.5 is ok. Therefore, in this test, we will consider it. In this study it was 2.24 which mean that is ok.\n\n\n\n### B3. Homocedasticity\n\nThe residuals are distribuided homogeneusly on the dependent variable. So they have iqual variance.\n\nEvaluation:\n- Diagrama de dispersión, Harrison-McCabe or Goldfeld-Quandt tests.\n\n\nGoldfeld-Quandt tests\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"lmtest\")\n\nlibrary(lmtest)\n\ngqtest(Intention_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGoldfeld-Quandt test\n\ndata:  Intention_lm\nGQ = 1.0384, df1 = 272, df2 = 271, p-value = 0.3781\nalternative hypothesis: variance increases from segment 1 to 2\n```\n\n\n:::\n:::\n\nH0: residuals have homogeneous variance.\nH1: residuals haven't homogeneous variance.\n\nAs p value was 0.3781 greater than 0.05, We have insufficient evidence to reject the null hypothesis. So we can say that residuals have homogeneous variance.\n\n\nHarrison-McCabe test\n\n::: {.cell}\n\n```{.r .cell-code}\nhmctest(Intention_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tHarrison-McCabe test\n\ndata:  Intention_lm\nHMC = 0.49002, p-value = 0.369\n```\n\n\n:::\n:::\n\nH0: residuals have homogeneous variance.\nH1: residuals haven't homogeneous variance.\n\nAs p value was 0.379 greater than 0.05, We have insufficient evidence to reject the null hypothesis. So we can say that residuals have homogeneous variance.\n\n\n\n### B4. Normality of Errors\n\nThe residuals show a normal distribution.\n\n\nEvaluation:\n- Residuals distribution, Q-Q plot, and Shapiro-Wilk test.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(residuals(Intention_lm)) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\nplot(Intention_lm)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n\n\n## C. Additional information\n\n\n### C1. Multicollinality: \n\nEvaluate if the IVs are redundant. This happen when VIs are highly correlated.\n\nEvaluation:\n- Tolerance (TOL) and Variance Inflation of Factor (VIF)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(Intention_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSN_Total BC_Total AT_Total \n2.984366 1.899331 2.991759 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(see)\nlibrary(performance)\n\nx<-check_collinearity(Intention_lm)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n     Term  VIF   VIF 95% CI Increased SE Tolerance Tolerance 95% CI\n SN_Total 2.98 [2.61, 3.44]         1.73      0.34     [0.29, 0.38]\n BC_Total 1.90 [1.70, 2.16]         1.38      0.53     [0.46, 0.59]\n AT_Total 2.99 [2.62, 3.45]         1.73      0.33     [0.29, 0.38]\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(x)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# los valores de VIF <6\n```\n:::\n\n\n\n### C2. Diagnostics.\n\nEvaluation:\n\n- Cook distances.\n\nvalues don't must be bigger than 1.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#the car package (Companion to Applied Regression)\n\n# Load the car package\nlibrary(car)\n\n# Compute influence measures, including Cook's distance\ninfluence <- influence.measures(Intention_lm)\n\n# Access Cook's distance from the influence object\ncook_dist <- influence$infmat[,7] #I put [,7] because that its the column that contains cook distances.\n\nsummary(cook_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n0.000e+00 4.156e-05 3.211e-04 2.811e-03 1.619e-03 1.340e-01 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot Cook's distance\nplot(cook_dist, pch = 19, main = \"Cook's Distance Plot\")\nabline(h = 4 * mean(cook_dist), col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nInterpretation: It's ok because any points is greater than 1.\n\n\n\n# Referencias\n\n- Dariusz Drążkowski & Radosław Trepanowski (2022) Reactance and perceived disease severity as determinants of COVID-19 vaccination intention: an application of the theory of planned behavior, Psychology, Health & Medicine, 27:10, 2171-2178, DOI: 10.1080/13548506.2021.2014060\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}